### PR TITLE
Unity 2020 LTS support and native platform implementation 

### LINKED ISSUE #22: WindowsMixedRealitySpatialMeshObserver.ConfigureObserverVolume Parameter name: _unity_self
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug
I added the spatial awareness system and configured the profile for windows universal:

image
But when running the application following exception is thrown every frame:

```
Value cannot be null.
Parameter name: _unity_self
  at (wrapper managed-to-native) UnityEngine.XR.WSA.SurfaceObserver.SetVolumeAsAxisAlignedBox_Injected(UnityEngine.XR.WSA.SurfaceObserver,UnityEngine.Vector3&,UnityEngine.Vector3&)

  at UnityEngine.XR.WSA.SurfaceObserver.SetVolumeAsAxisAlignedBox (UnityEngine.Vector3 origin, UnityEngine.Vector3 extents) <0x219beb49840 + 0x00062> in <c5fbc3025773463c979131b886ed2b73>:0 

  at XRTK.WindowsMixedReality.SpatialObservers.WindowsMixedRealitySpatialMeshObserver.ConfigureObserverVolume (UnityEngine.Vector3 newOrigin, UnityEngine.Vector3 newExtents) [0x00025] in C:\workspaces\mxr-xrtk\Library\PackageCache\com.xrtk.wmr@7b8d08a2318b9c5190608741debfb2d7078bdae7\SpatialObservers\WindowsMixedRealitySpatialMeshObserver.cs:137 

  at XRTK.WindowsMixedReality.SpatialObservers.WindowsMixedRealitySpatialMeshObserver.Update () [0x00062] in C:\workspaces\mxr-xrtk\Library\PackageCache\com.xrtk.wmr@7b8d08a2318b9c5190608741debfb2d7078bdae7\SpatialObservers\WindowsMixedRealitySpatialMeshObserver.cs:74 

  at XRTK.Services.MixedRealityToolkit.UpdateAllServices () [0x00095] in C:\workspaces\mxr-xrtk\Library\PackageCache\com.xrtk.core@d4be87365d4a56d22bb908f3acc8b409cf10240c\Services\MixedRealityToolkit.cs:1273 
0x00007FF65E1CB0BC (Unity) StackWalker::GetCurrentCallstack
0x00007FF65E1CE571 (Unity) StackWalker::ShowCallstack
0x00007FF65C938E55 (Unity) GetStacktrace
0x00007FF65EBE8A00 (Unity) DebugStringToFile
0x00007FF65E1F9BB9 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x00000219B4E3413B (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x00000219B4E33FFB (Mono JIT Code) [DebugLogHandler.cs:10] UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[]) 
0x00000219B4E33691 (Mono JIT Code) [Logger.cs:61] UnityEngine.Logger:Log (UnityEngine.LogType,object) 
0x00000219BB57142D (Mono JIT Code) [Debug.bindings.cs:127] UnityEngine.Debug:LogError (object) 
0x00000219B731D5F3 (Mono JIT Code) [MixedRealityToolkit.cs:1277] XRTK.Services.MixedRealityToolkit:UpdateAllServices () 
0x00000219B731CBFB (Mono JIT Code) [MixedRealityToolkit.cs:710] XRTK.Services.MixedRealityToolkit:Update () 
0x00000219E006CED8 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FFED8F1BBCB (mono-2.0-bdwgc) [mini-runtime.c:2809] mono_jit_runtime_invoke 
0x00007FFED8EA2252 (mono-2.0-bdwgc) [object.c:2919] do_runtime_invoke 
0x00007FFED8EAB25F (mono-2.0-bdwgc) [object.c:2966] mono_runtime_invoke 
0x00007FF65E15CD26 (Unity) scripting_method_invoke
0x00007FF65E157015 (Unity) ScriptingInvocation::Invoke
0x00007FF65E113702 (Unity) MonoBehaviour::CallMethodIfAvailable
0x00007FF65E113AA6 (Unity) MonoBehaviour::CallUpdateMethod
0x00007FF65D842014 (Unity) BaseBehaviourManager::CommonUpdate<BehaviourManager>
0x00007FF65D84A614 (Unity) BehaviourManager::Update
0x00007FF65DC79163 (Unity) `InitPlayerLoopCallbacks'::`2'::UpdateScriptRunBehaviourUpdateRegistrator::Forward
0x00007FF65DC62678 (Unity) ExecutePlayerLoop
0x00007FF65DC62756 (Unity) ExecutePlayerLoop
0x00007FF65DC67310 (Unity) PlayerLoop
0x00007FF65C9873F0 (Unity) PlayerLoopController::UpdateScene
0x00007FF65C984469 (Unity) Application::TickTimer
0x00007FF65CC440FB (Unity) MainMessageLoop
0x00007FF65CC4DB07 (Unity) WinMain
0x00007FF65F57FB2E (Unity) __scrt_common_main_seh
0x00007FFF56287974 (KERNEL32) BaseThreadInitThunk
0x00007FFF582FA271 (ntdll) RtlUserThreadStart
```

## To Reproduce
1. Activate spatial awareness system
2. Create (clone) custom profile (issue occurs with default profile too)
3. Run app

## Your Setup (please complete the following information)

- Unity Version 2019.1.1f1
- XRTK Version 0.1.9

## Target Platform (please complete the following information)

- WMR immersive
- HoloLens

### LINKED ISSUE #50: HoloLensWorldManager failed to return a world coordinate system!
## Describe the bug
When running the XRTK in the current insider build for windows, the following error is repeatedly spammed into the console:

```
HoloLensWorldManager failed to return a world coordinate system!
UnityEngine.XR.WSA.SurfaceObserver:SetVolumeAsAxisAlignedBox(Vector3, Vector3)
XRTK.WindowsMixedReality.SpatialObservers.WindowsMixedRealitySpatialMeshObserver:ConfigureObserverVolume(Vector3, Vector3) (at Library/PackageCache/com.xrtk.wmr@0.1.9/SpatialObservers/WindowsMixedRealitySpatialMeshObserver.cs:131)
XRTK.WindowsMixedReality.SpatialObservers.WindowsMixedRealitySpatialMeshObserver:Update() (at Library/PackageCache/com.xrtk.wmr@0.1.9/SpatialObservers/WindowsMixedRealitySpatialMeshObserver.cs:68)
XRTK.Services.MixedRealityToolkit:UpdateAllServices() (at Library/PackageCache/com.xrtk.core@0.1.29/Services/MixedRealityToolkit.cs:1262)
XRTK.Services.MixedRealityToolkit:Update() (at Library/PackageCache/com.xrtk.core@0.1.29/Services/MixedRealityToolkit.cs:683)
```

## To Reproduce
Target the UWP platform, run.

## Information(please complete the following information):
 - Version: 2019.1.14
- Release package

### LINKED ISSUE #83: Update package to use fully native APIs
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

As part of our move to break dependencies on the XR SDK manager and plugin architecture, we should make strides to try and update this package to use the native windows APIs.

### LINKED ISSUE #144: Build System doesn't properly check min sdk requirements for platforms.
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

Recently we updated our build machines, but they failed in unexpected ways when the windows uwp sdks were not installed. Theoretically Unity _should_ have complained and threw an appropriate error, but didn't. We could add a check in the build pipeline to validate sdk dependencies.

### PR DESCRIPTION
**Pull request by StephenHodgson**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview

Support for Unity Editor 2020+ as well as native platform implementations for existing services and data proviers.

## Changes

- Fixes: #83
- Fixes: #22 
- Fixes: #50 
- Fixes: #144

## Breaking Changes

- Breaks all old WMR platform services and providers. Upgrade and migration guide TBA

## Related Changes

- https://github.com/XRTK/XRTK-Core/pull/815

## Known Issues

- [ ] Hand tracking works, but isn't synced with the local player space. Seems to drift as you walk and turn around the space.
- [ ] Spatial Meshing doesn't seem to show up/get generated.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@FejZa What all is needed to finish up this PR?

**Comment by StephenHodgson** [comment]
image
@FejZa

**Comment by FejZa** [comment]
@StephenHodgson sorry for the delay. This needs restoring support for WMR gestures using native APIs and testing the spatial mapping.

**Comment by FejZa** [comment]
I'll look into that error.

**Comment by StephenHodgson** [comment]
Just gonna sync the discussion and feedback from Discord here:

- Hand tracking works, but isn't synced with the local player space. Seems to drift as you walk and turn around the space.
- Spatial Meshing doesn't seem to show up/get generated.

**Pull request merged**
