### PR TITLE
Fix WMR hand controller profiles referencing SDK

### PR DESCRIPTION
**Pull request by FejZa**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview

Created duplicate profiles required for the hand controller on the WMR platform. It's unfortunate that we have to
duplicate profiles this way but until we find another solution, if that's needed, this fixes the issue with the profiles being broken
in the current preview release.

## Changes

- Created profiles for WMR hand controller configuration

### CODE REVIEW

**Comment by StephenHodgson** [comment]
We can probably remove the ones in the SDK then

**Comment by FejZa** [comment]
They are unfortunately needed for the simulated hand still

**Comment by StephenHodgson** [comment]
Shouldn't the simulated hand profiles stand on their own?

**Comment by FejZa** [comment]
Not sure I can follow. Simulated hands live in XRTK-Core and Core does not have any profiles right? So simulated needs to rely on SDK being imported to work.

**Comment by StephenHodgson** [comment]
Right, so then why is it needed for simulated hands in your [prev comment](https://github.com/XRTK/WindowsMixedReality/pull/102#issuecomment-729884470)?

**Comment by FejZa** [comment]
If we remove the hand input profiles from SDK, then simulation will be broken since it's using them.

**Comment by StephenHodgson** [comment]
I get that we need to keep the hand profiles required, but just remove the wmr specific ones.

**Comment by StephenHodgson** [comment]
How did we fix this in Oculus @SimonDarksideJ ?

**Comment by FejZa** [comment]
Ah now I understand haha. There was no WMR specifc ones in SDK. So far I've been using the same profiles for Simulation, WMR and Oculus. But now I'll have to have each platform have their own. Although they are the same value wise.

**Comment by SimonDarksideJ** [comment]
Oculus has the same issue @StephenHodgson , We found that Oculus and WMR are sharing the Hands Configuration in the SDK.  Since SDK is optional, it would break those platforms if it was there.

Same issue as we had with the controllers, which was fixed by creating profiles IN those platforms and assigning them correctly.

**Comment by FejZa** [comment]
Oculus was fixed by doing the same thing. @SimonDarksideJ just did it for Oculus Touch etc. but not for hands though. I think hands weren't merged back then. So I'll catch up now and do the same thing for Oculus hands.

**Review by SimonDarksideJ — APPROVED** [review]
Looks good, will just have to wait until it's merged and a new preview asset generated to test.

**Review by StephenHodgson — APPROVED** [review]

**Pull request merged**
