### PR TITLE
Updated WMR controller config layout, to support #664

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview

WMR Controller Input Action mappings were depending on the OpenVR controller input action mappings, however when these were moved to the WMR package, the mappings were not moved too.

## Changes

- Added Controller Input Action mappings for WMR controllers
- Reorganized assets to match SDK

- Fixes: https://github.com/XRTK/XRTK-Core/issues/664

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Were these files removed from another package and added to this one?

**Comment by SimonDarksideJ** [comment]
> Were these files removed from another package and added to this one?
Err, no.

If I removed them from the SDK, then OpenVR wouldn't work :D

**Comment by StephenHodgson** [comment]
Well we get conflicts if they're not removed? Or are these changed enough to be unique?

**Comment by SimonDarksideJ** [comment]
> Well we get conflicts if they're not removed?

again, tested and no, it doesn't conflict. As when we import the profiles from their hidden folders, all the GUID's get regenerated.  So no conflicts

**Review by FejZa — APPROVED** [review]
Even though it's the "same" profile I like having the copies in each platform package instead of sharing across packages.

**Pull request merged**
